version: '3.4'

services:
  sportnetdb:
    container_name: sportnet-db
    build:
      context: .
      dockerfile: Dockerfile_db
    ports:
      - 7180:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
      - SQL_PASSWORD=password123
    networks:
      - servicesnetwork

networks:
  servicesnetwork:
