FROM mcr.microsoft.com/mssql/server:2019-latest

COPY sportnet.bak /tmp/sportnet.bak

# RUN /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P password@12345# -Q "RESTORE DATABASE SportNet FROM DISK='/tmp/sportnet.bak' WITH MOVE 'SportNet' TO '/var/opt/mssql/data/SportNet.mdf', MOVE 'SportNet_log' TO '/var/opt/mssql/data/SportNet_log.ldf'"

CMD ["/opt/mssql/bin/sqlservr"]