apiVersion: apps/v1
kind: Deployment
metadata:
  name: sportnetdb
  labels:
    app: sportnetdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sportnetdb
  template:
    metadata:
      labels:
        app: sportnetdb
    spec:
      containers:
        - name: sportnetdb
          image: localhost:32000/sportnetdbimage
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "password@12345#"
            - name: SQL_PASSWORD
              value: "password123"
          volumeMounts:
            - name: sportnetdb-data
              mountPath: /var/opt/mssql
      volumes:
        - name: sportnetdb-data
          persistentVolumeClaim:
            claimName: sportnetdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sportnetdb-service
spec:
  selector:
    app: sportnetdb
  ports:
    - name: db-port
      protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
